# Generated by Django 5.0.4 on 2024-04-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.IntegerField()),
                ('steps', models.TextField()),
                ('image', models.CharField(max_length=500)),
            ],
        ),
    ]
